name: 'Install the Solana CLI'
description: 'Install the Solana CLI using a local Dockerfile'

inputs:
  version:
    description: 'Solana version to use'
    required: true
    default: '2.0.0'

runs:
  using: 'docker'
  image: 'Dockerfile'
  # env:
  #   SOLANA_VERSION: ${{ inputs.version }}
  args:
    - ${{ inputs.version }}
    # - 'solanafoundation/solana-verifiable-build:${{ inputs.version }}'
