# action.yml
name: "Setup Solana Environment"
description: "Sets up Solana CLI environment using the verified builds docker images"

inputs:
  version:
    description: "Solana version to use"
    required: true
    default: "2.0.0"

outputs:
  container-image:
    description: "The Docker image to use for the job"
    value: solanafoundation/solana-verifiable-build:${{ inputs.version }}

# Example of how to use the action in a workflow
runs:
  using: "composite"
  steps:
    - name: Set container for job
      shell: bash
      run:
        echo "container=solanafoundation/solana-verifiable-build:${{ inputs.version }}" >>
        $GITHUB_ENV
