ARG CONTAINER=solanafoundation/solana-verifiable-build:2.0.0
FROM $CONTAINER


# ARG SOLANA_VERSION
# FROM solanafoundation/solana-verifiable-build:${SOLANA_VERSION}

# ENV SOLANA_VERSION=${SOLANA_VERSION}
