ARG CONTAINER=solanafoundation/solana-verifiable-build:1.18.0
FROM $CONTAINER
CMD /bin/bash

# ARG SOLANA_VERSION
# FROM solanafoundation/solana-verifiable-build:${SOLANA_VERSION}

# ENV SOLANA_VERSION=${SOLANA_VERSION}
